# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uaddress', models.CharField(max_length=200)),
                ('ucountry', models.CharField(choices=[('India', 'India'), ('China', 'China')], default='India', max_length=200)),
                ('uzipcode', models.IntegerField()),
                ('uemail', models.EmailField(max_length=254)),
                ('usex', models.CharField(max_length=200)),
                ('ulanguage', models.CharField(max_length=200)),
                ('uabout', models.CharField(max_length=200)),
                ('uimage', models.ImageField(blank=True, upload_to='imageFolder/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
